import Head from "next/head";
import Image from "next/image";
import Main from "../components/main";
import Layout from "../components/layout";
import ServiceCards from "../components/serviceCards";

export default function Home() {
  return (
    <Main>
      <Head>
        <title>Ally Counseling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ally.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Icons+Outlined"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="text-center px-4 py-8">
        <h4>You deserve your best life</h4>
        <Layout>
          <p className="text-2xl font-serif mt-4 mx-2">
            Unlock your full potential with therapy. counseling, and coaching
            services with Ally Counseling.
          </p>
        </Layout>
      </div>
      <Layout>
        <ServiceCards />
      </Layout>
      <div className="bg-gray-100 pt-4 pb-8 mt-4">
        <Layout px={2}>
          <h4 className="py-2 ml-4 text-center">Welcome to Ally Counseling</h4>

          <p className="my-3 font-serif tracking-wide">
            We’re a team of talented therapists dedicated to helping people
            improve their lives. Ally Counselors strongly believe that everyone
            deserves a wonderful life and is capable of reaching that goal. Life
            can be challenging and sometimes you need an Ally who has the
            knowledge, skills, and determination to help you live life to the
            fullest. Whether aspiring to improve your personal life, academics,
            career, relationships, Ally Counselors help people bring out their
            best so they can make positive and lasting changes in their lives.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 justify-items-center">
            <div
              className="bg-cover h-80 m-2 p-2 max-w-sm  flex flex-col rounded-lg shadow-lg"
              style={{ "backgroundImage": "url(/improve-wellbeing.jpg)" }}
            >
              <h3 className="text-center flex-grow px-14">Improve Wellbeing</h3>
            </div>
            <div
              className="bg-cover h-80 m-2 p-2 max-w-sm  flex flex-col rounded-lg shadow-lg"
              style={{ "backgroundImage": "url(/tackle-depression.jpg)" }}
            >
              <h3 className="text-center flex-grow px-10">
                Tackle Depression and Anxiety
              </h3>
            </div>
            <div
              className="bg-cover h-80 m-2 p-2 max-w-sm  flex flex-col rounded-lg shadow-lg"
              style={{ "backgroundImage": "url(/find-balance.jpg)" }}
            >
              <h3 className="text-center flex-grow px-10">
                Find Balance in Your Life
              </h3>
            </div>
            <div
              className="bg-cover h-80 m-2 p-2 max-w-sm  flex flex-col rounded-lg shadow-lg"
              style={{ "backgroundImage": "url(/mindful.jpg)" }}
            >
              <h3 className="text-center flex-grow px-10">
                Develop Mindfulness
              </h3>
            </div>
          </div>
        </Layout>
      </div>
      <div className="pt-4 pb-8">
        <Layout>
          <h4 className="py-2 ml-4">Ally Counselors</h4>
        </Layout>
      </div>
    </Main>
  );
}
