import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import Hero from "../components/hero";

export default function Home() {
  return (
    <>
      <Hero />
      <Layout>
        <Head>
          <title>Ally Counseling</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/ally.ico" />
        </Head>

        <main className="main">
          <h1>Ally Counseling</h1>
          <p className="font-serif">Serif font where hero image will go</p>
          <p className="mt-20 font-sans">Services Section</p>
          <p className="mt-20 font-sans">
            Welcome to Ally Counseling (About Ally Counseling)
          </p>
          <p className="mt-5 font-sans">
            We’re a team of talented therapists dedicated to helping people
            improve their lives. Ally Counselors strongly believe that everyone
            deserves a wonderful life and is capable of reaching that goal. Life
            can be challenging and sometimes you need an Ally who has the
            knowledge, skills, and determination to help you live life to the
            fullest. Whether aspiring to improve your personal life, academics,
            career, relationships, Ally Counselors help people bring out their
            best so they can make positive and lasting changes in their lives
          </p>
          <ul className="list-disc list-inside">
            <li>Improve your wellbeing and feel better</li>
            <li>Gain the insight you need to succeed</li>
            <li>Discover your true potential</li>
            <li>Learn the science behind wellbeing</li>
            <li>Let go of the things that are holding you back</li>
            <li>Tackle depression and anxiety</li>
            <li>Find balance in your life</li>
            <li>Learn Mindfulness for wellness and performance</li>
            <li>Improve your interpersonal skills</li>
            <li>Develop your emotional IQ</li>
          </ul>
          <p className="mt-20 font-sans">Ally Counselors</p>
          <p className="mt-20 font-sans">And some font sans</p>
          <p className="link-classic">Click here</p>
        </main>
      </Layout>
    </>
  );
}
